package com.pfe.Bank.model;

public enum Responses {
    PROFESSION,
    DATENAISSANCE,
    SECTEURACTIVITE,
    CHIFFREAFFAIRE,
    DENOMINATIONSOCIALE,
    MntEnConsolidation,
    ANCIENNETEIMPAYES,
    IMPAYE,
    SOLDEMOYENANNUELANNEEN,
    MONTANTIMPAYES,
    REGULARITEECHEANCES,
    RATIOENGAGEMENTCDR,
    SOLDEMOYENANNUEANNEEN1,
    CLASSERISQUELEGACY,
    IDENTIFIANTNATIONAL,
    DATEDENAISSANCE,
}
